### ISSUE TITLE
cant parse hebrew

### ISSUE THREAD

**Issue by idshklein** [a-b-street/docs#42]
Hi, I played with the tel aviv net and the software crashed, this message was in the output file
[2023-11-24T08:46:41Z WARN  usvg_text_layout] No fonts with a ם/U+5DD character were found.

**Comment by idshklein** [comment]
maybe the crash was because of this:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Ring has duplicate adjacent points near Pt2D(0, 0)', geom\src\polygon.rs:164:46
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-11-24T08:53:26Z INFO  abstio::io_native] Wrote data/player/camera_state/il/tel_aviv/center.json
[2023-11-24T08:53:26Z INFO  abstio::io_native] Wrote data/player/maps.json
thread 'main' panicked at '".\\binaries\\fifteen_min.exe" "data/system/us/seattle/maps/montlake.bin" failed', abstutil\src\process.rs:9:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

********************************************************************************
[2023-11-24T08:53:27Z INFO  abstio::io_native] Wrote data/player/camera_state/us/seattle/montlake.json
[2023-11-24T08:53:27Z INFO  abstio::io_native] Wrote data/player/maps.json
Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 00:00:00.0

Camera:
{ "cam_x": 97.23859006045129, "cam_y": -63.174256402636445, "cam_zoom": 0.4403113594989896 }

No edits

Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
********************************************************************************

**Comment by dabreegster** [comment]
Thanks for reporting! The crash was due to some geometry problem, I'll look into it when I get time.

The warning about fonts can also be fixed, if you can point me to a (preferably Noto-based) font that we can wire up in https://github.com/a-b-street/abstreet/blob/9181106cfe8b12820ce6774479e3f6183518e01c/map_gui/src/load.rs#L34
